<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>rosbag_timing_inspector</name>
  <version>1.0.1</version>
  <description>
    GUI tool to visualize and analyze message timing from ROS2 bags (mcap or db3).
  </description>

  <maintainer email="joseluisblancoc@gmail.com">Jose Luis Blanco-Claraco</maintainer>
  <author email="joseluisblancoc@gmail.com">Jose Luis Blanco-Claraco</author>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rosbag2_cpp</depend>
  <depend>rosbag2_storage</depend>
  <build_depend>opengl</build_depend>
  <build_depend>libglfw3-dev</build_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
